name: vgo_flutter_app
description: "VGo"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.35+35

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  salomon_bottom_bar: ^3.3.2
  carousel_slider: ^4.2.1
  otp_text_field: ^1.1.3
  dio: ^5.4.2+1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  string_validator: ^1.0.2
  another_flushbar: ^1.12.30
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  webview_flutter: ^4.7.0
  cool_alert: ^2.0.1
  basic_utils: ^5.7.0
  flutter_launcher_icons: ^0.13.1
  file_picker: ^6.0.0+1
  permission_handler: ^11.3.1
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  intl: ^0.19.0
  custom_timer: ^0.2.3
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.4.0
  zego_uikit: ^2.22.3
  zego_uikit_prebuilt_call: ^4.11.0
  flare_flutter: ^3.0.2
  device_info: ^2.0.3
  modal_bottom_sheet: ^3.0.0
  google_maps_flutter: ^2.6.1
  maps_launcher: ^2.2.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flip_card: ^0.7.0
  sizer: ^3.0.3
  smooth_page_indicator: ^1.2.0+3
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/vgo_logo.png"


  flutter_lints: ^3.0.0
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0

  flutter_native_splash:
    image: assets/images/logo/vgo_logo.png
    color: "#234324"

    android: false
    ios: false



  android_gravity: center

  android_fullscreen: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  assets:
    - assets/
    - assets/images/logo/vgo_logo.png
    - assets/images/login/vgo_login.jpg
    - assets/images/service/pick_a_service_black.png
    - assets/images/service/user_avatar.png
    - assets/images/home/right_icon.svg
    - assets/images/home/bell_notification.svg
    - assets/images/common/ic_cart.svg
    - assets/images/common/ic_customer_care.svg
    - assets/images/common/down_arrow_round.svg
    - assets/images/profile/user_avatar.svg
    - assets/images/profile/edit_icon.svg
    - assets/images/profile/ic_award.svg
    - assets/images/profile/qr_code_sharp_icon.svg
    - assets/images/profile/qr_code_sharp_icon.svg
    - assets/images/wallet/no_pictures.png
    - assets/images/services/mobile_transfer.svg
    - assets/images/banner/banner1.png
    - assets/images/banner/banner2.png
    - assets/images/banner/banner3.png
    - assets/images/services/left_arrow.svg
    - assets/images/services/right_arrow.svg
    - assets/images/services/ic_needle_arrow_right.svg
    - assets/images/services/ic_services_bg.png
    - assets/images/services/ic_services_menu_bg.png
    - assets/images/services/correct.png
    - assets/images/services/bank.svg
    - assets/images/services/circle.png
    - assets/images/services/ic_lock.svg
    - assets/images/services/upi.svg
    - assets/images/services/ic_upload_image.svg
    - assets/images/kyc/location.png
    - assets/images/kyc/ic_location.svg
    - assets/images/kyc/delete.png
    - assets/images/kyc/years.svg
    - assets/images/common/tick.svg
    - assets/images/home/netflix.png
    - assets/images/service/arrow.svg
    - assets/images/services/chat_bg.png
    - assets/images/services/ic_send.svg
    - assets/images/logo/vgo_logo.png
    - assets/images/service/transagent.png
    - assets/images/services/trans_order.png
    - assets/images/wallet/wallet.svg
    - assets/images/wallet/wallet.png
    - assets/images/bank/axis_bank.png
    - assets/images/bank/icici_bank.png
    - assets/images/bank/hdfc_bank.jpg
    - assets/images/bank/paytm.jpg
    - assets/images/bank/phonepe.jpg
    - assets/images/bank/gpay.png
    - assets/images/home/coin1.png
    - assets/images/home/coin_new.png
    - assets/images/home/down_arrow.svg
    - assets/images/home/down_arrow.png
    - assets/images/services/ic_success.png
    - assets/images/services/ic_success_banner.png
    - assets/images/services/ic_success.svg
    - assets/images/services/ic_failure.svg
    - assets/images/map/map_icon.png
    - assets/images/home/ic_qr_code.svg
    - assets/images/jobs/ic_jobs_placeholder.png
    - assets/images/sep/ic_uptrend_arrow.svg
    - assets/images/sep/ic_bank_logo.svg
    - assets/images/sep/ic_share.svg
    - lib/src/view/
    - lib/src/view/home/
    - lib/src/view/home/widget/
    - lib/src/view/home/widget/coin/
    - lib/src/view/home/company_info/
    - lib/src/view/team/
    - lib/src/view/team/store/
    - lib/src/view/team/product/
    - lib/src/view/team/freelancer/
    - lib/src/view/login/
    - lib/src/view/bottom/
    - lib/src/view/common/
    - lib/src/view/wallet/
    - lib/src/view/account/
    - lib/src/view/profile/
    - lib/src/view/profile/user_category/
    - lib/src/view/activity/
    - lib/src/view/activity/kyc/
    - lib/src/view/activity/kyc/address/
    - lib/src/view/activity/kyc/profile/
    - lib/src/view/activity/kyc/education/
    - lib/src/view/activity/kyc/experience/
    - lib/src/view/activity/transagent/
    - lib/src/view/activity/transagent/upi/
    - lib/src/view/activity/transagent/inbound/
    - lib/src/view/activity/transagent/outbound/
    - lib/src/view/register/
    - lib/src/view/services/
    - lib/src/view/services/order/
    - lib/src/view/services/stores/
    - lib/src/view/services/transfer/
    - lib/src/view/services/add_new_recipient/
    - lib/src/view/services/bank_upi_transfer/
    - lib/src/view/services/vgo_wallet_transfer/










